import {
	CKBTC_LEDGER_CANISTER_ID,
	CKETH_LEDGER_CANISTER_ID,
	CKUSDC_LEDGER_CANISTER_ID,
	CKUSDT_LEDGER_CANISTER_ID,
	ICP_LEDGER_CANISTER_ID,
	USDX_LEDGER_CANISTER_ID
} from '@constants/app.constants';

export const getIcrcLedgerCanisterIds = () => [
	USDX_LEDGER_CANISTER_ID,
	CKUSDC_LEDGER_CANISTER_ID,
	ICP_LEDGER_CANISTER_ID,
	CKBTC_LEDGER_CANISTER_ID,
	CKETH_LEDGER_CANISTER_ID,
	CKUSDT_LEDGER_CANISTER_ID
];
